#!/usr/bin/env python3

import sys
import itertools
from awsv2_auth import AwsV2Auth


class Request(object):
    def __init__(self, method, url, headers):
        self.method = method
        self.url = url
        self.headers = SemiFrozenDict()
        for k in headers:
            self.headers[k] = headers[k]


class SemiFrozenDict(dict):
    def __setitem__(self, key, val):
        if key == "x-amz-date":
            return
        dict.__setitem__(self, key.lower(), val)

    def __getitem__(self, key):
        return dict.__getitem__(self, key.lower())

    def get(self, key, default):
        return dict.get(self, key.lower(), default)


auth = AwsV2Auth("AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY")

method, remaining = sys.stdin.readline().rstrip().split(" ", 1)
url, version = remaining.rsplit(" ", 1)
headers = {k: v.lstrip()
           for k, v in [l.rstrip().split(":", 1)
                        for l in itertools.takewhile(
                                lambda l: ":" in l, sys.stdin)]}
request = Request(method, url, headers)
signed = auth(request)
print(signed.headers['Authorization'], end='')
